### ISSUE TITLE
Performance hit vs. PSVshell (in Wipeout2048 at least)

### ISSUE THREAD

**Issue by rmsa5** [GrapheneCt/PSVshellPlus#11]
Hi there,
thanks for your good work.

I've been noting performance issues when using PSVshellPlus vs. PSVshell

Specific test case:

- Game: Wipeout2048 USA
- Extra settings: Vitagrafix (960x544, 60 fps)
- SD2Vita (with high end Sandisk Extreme Pro card, no corruption whatsoever)
- and the usual set of carefully curated plugins (can provide full config upon request)

Compared, with full overclocking, for each of the 2 plugins (PSVshellPlus 1.2, PSVshell 1.1). Made sure when switching both plugins to remove the profiles (as per PSVshellPlus install instructions)

Same exact situation (track, difficulty, at race start during start countdown). To be noted that performance differences remain equally as significant  and notable (especially with this high paced game) all along the race.

Tried to make screenshots but they do not convey the difference in performance (I suppose because race start still loads stuff in the background). I estimate an average 7~10 fps difference between both plugins (in favour of PSVshell).

Will need to find more time to test on other intensive fast paced games to see if this happens too. Any game suggestions are welcome.

Thanks in advance. Let me know if I can provide further info to help debug.

**Comment by mightysashiman** [comment]
Just realised I uploaded the wrong screenshot for PSVShell with full-overclock (it shows post race start with no CPU controlled ships to render onscreen so of course FPS is going to be higher). Let me correct this in the upcoming minutes.

**Comment by GrapheneCt** [comment]
Please double check everything and make sure you don't have other OC plugins active. Does quick menu report correct clocks? These values come directly from kernel and can't be wrong.

**Comment by rmsa5** [comment]
Hi there,
can still reproduce.
I switched (comment out) between PSVshell (the classic one) and PSVshell_Plus.
Run Wipeout 2048, run the same exact track, FPS is around 40-50 fps with PSVshell classic, around 27 fps with PSVshell_Plus.

In PSVshell classic, I set all 4 available settings to max available: CPU:500, ES4:222, BUS:222, XBR:166. (it’s saved to Profile PCSA00015)
In PSVshell_plus, I set all 3 available settings to max available: CPU:500, GPU:111, and XBAR:166, tick lock all 3 (not sure what the lock does more though), press the “OK" button to save.

**UPDATE: I’ve found the bug: I cannot push GPU above 111 unless I previously tick GPU lock. I can then OC GPU to 222. But if I unlock it, it goes right back to 111.**

2 remarks:
- Would you mind documenting what the “lock” tickbox do please?
- The left button reads “OK” rather than “Save”. The screenshot seems off.

Difference is like night and day.

I’m monitoring FPS with ViBeS plugin.

**Comment by GrapheneCt** [comment]
Is it not obvious from your own description what "lock" tickbox does and why you are having this issue? Vita OS tries to always keep clocks within modes set by system software/application, so all clocks must be locked to prevent system from changing them back. Original PSVshell does this implicitly when you manually set clock.
