### ISSUE TITLE
Please rename CPU frequency 500 MHz to 494 MHz.

### ISSUE THREAD

**Issue by Icon125** [GrapheneCt/PSVshellPlus#12]
This is the true clock.
"500MHz" was always a false rounding-up.

**Comment by GrapheneCt** [comment]
1. It's actually 499 MHz.
2. In official docs Sony prefers to round it up to 500 MHz too.
3. 500 MHz looks nicer.

**Comment by Icon125** [comment]
Fair enough, thank you!
