### ISSUE TITLE
PSVShell Plus never worked

### ISSUE THREAD

**Issue by Diego9000** [GrapheneCt/PSVshellPlus#15]
Hello! As by my title, it never worked and no error appears.
And it's not exclusively to the latest version, no version ever worked. 
The install process was done countless time, so I'm pretty sure it's not on the install process the issue.

But just to confirm, I've:

- Disabled the original PSVShell
- Set up at the config.txt the PSVShellPlus
- Placed PSVshellPlus_Kernel.skprx and PSVshellPlus_Shell.suprx at the ur0:tai/ folder
- Deleted the original PSVShell profiles (ur0:data/PSVshell/profiles/)
- Placed psvshell_plugin.rco inside the PSVShell folder
- Rebooted the vita

I've the PS Vita PCH-2000 at 3.68 firmware
I've the h-encore (FinalHE_v1.92)
No enso

I've attached my config.txt in case it's needed.
[config.txt](https://github.com/GrapheneCt/PSVshellPlus/files/9592075/config.txt)

**Comment by Diego9000** [comment]
Installing enso fixed the issue.
So, I think it should be stated in the install process that enso is mandatory to be able to use this plugin.

**Comment by Darthagnon** [comment]
Never worked for me, even with Enso 3.65

**Comment by boozook** [comment]
Same problem for me, but with enso.

**Comment by SlowStopper** [comment]
Same here, I was on fw 3.74, installed Enso 3.65 (fresh install), never setup PSVShell (went straight to PSVShell Plus), pressing select+Up/Down doesn't do anything. If someone replies to this post within few days, I'll be keeping the setup to troubleshoot, if not -> move to PSVShell.

**Comment by GrapheneCt** [comment]
Please tell me where in the readme does it say to press select+Up/Down.

**Comment by SlowStopper** [comment]
If we're playing sarcasm, please tell me where in the readme does it say how to trigger the menu?

Since it's not explained, I assumed it's triggered the same way as for PSVShell.

**Comment by GrapheneCt** [comment]
It says "full Quick Menu integration". If you don't know what Quick Menu is you should probably read PlayStation®Vita User's Guide before you continue using your PlayStation®Vita system.

**Comment by SlowStopper** [comment]
Funny you should mention that, as up to this date I did not realize that this menu can be scrolled 😅.

Thanks for your patience in explaining me how it works :) Happy New Year!
