### ISSUE TITLE
No bus clock speed monitoring/adjustment

### ISSUE THREAD

**Issue by EnekoT2001** [GrapheneCt/PSVshellPlus#16]
There's no way to see or adjust bus clock speed and idk why, any other OC plugin has that and it can be significant especially for loading screens or data transfer via ftp and such, almost no software uses the highest clock speed for that either, so i like to set it to the maximum myself, apart from that this sure is like a version 2.0 from the original psvshell

**Comment by GrapheneCt** [comment]
CPU bus clock speed on Vita is always set to maximum possible value (222 MHz) unless application intentionally underclocks it, which can only be done by homebrew, not officially released applications. So adding option to adjust this clock speed is pointless.
