### ISSUE TITLE
Dynamic CPU clock for better battery life

### ISSUE THREAD

**Issue by Mael-Kratek** [GrapheneCt/PSVshellPlus#17]
Could you implement this feature, as well as more cpu clocks between 333-444MHz? Rangi has done this on his fork of the OG PSVShell, though from a glance, it seems RaanGi hasn't actually properly implemented those other clockspeeds. The only one that looks like it'll actually work is 468MHz since he bypasses kscePowerSetArmClockFrequency and uses ScePervasive directly for that one.

Here’s the link for Rangi’s fork: https://github.com/RaanGi/PSVshell

**Comment by Mael-Kratek** [comment]
Update: Bytho’s pull request fixes the frequencies that weren’t working.

https://github.com/RaanGi/PSVshell/pull/3

**Comment by GrapheneCt** [comment]
After some experiments with dynamic clocking that I did some time ago I decided to stop working on this feature since the benefit it provides is minimal. Reducing CPU voltage is much more effective but it makes system very unstable so it's not an option either.
