### ISSUE TITLE
Cannot compile with visual studio 2007

### ISSUE THREAD

**Issue by lencil** [GrapheneCt/PSVshellPlus#18]
I've installed the vdsuite as https://github.com/Vita-Development-Suite/doc mentioned. And I also Installed the sce visual studion 2007 plugin. But when I compile, cannot open source file "taihen.h". As I know this header file only in vitasdk.org. Does I need install vitasdk.org too?
After I installed vitasdk.org in msys2，I set the include path to the vitasdk so that the project could find "taihen.h", but an error occured that about "taihen.h" only support gcc.
So I stuck here.
And also I want to know, which version of vdsuite-libraries in https://bin.shotatoshounenwachigau.moe/vdsuite/ should I installed.
Thank you!

**Comment by GrapheneCt** [comment]
Source code provided with this plugin currently cannot be compiled with any public SDKs.
