### ISSUE TITLE
add button only mods

### ISSUE THREAD

**Issue by OilSubjectLoss7** [GrapheneCt/PSVshellPlus#7]
i keep clicking the background i almost bricked my vita while setting up the cpu, i have to use touchscreen to avoid that.

**Comment by GrapheneCt** [comment]
What exactly are you requesting and how did you manage to almost brick your Vita from quick menu? You can already control it with physical buttons if the feature is enabled in Settings app.

**Comment by inthavoc** [comment]
I think he had some other app on the background.
When using the quick menu the buttons still register in the back, if you have a game for example with pause menu while you change the settings, pressing X in the QuickMenu will also press Resume in the game.

**Comment by GrapheneCt** [comment]
Buttons do not register in the app when quick menu is opened. If they do, you have installed something that breaks the way system should operate and you should uninstall it.
